---
title: ""
lag: es
format: 
  pdf:
    documentclass: article
    fontsize: 12pt
    linestretch: 1.5
    geometry: "margin=1in"
    number-sections: false
    colorlinks: true
    linkcolor: blue
    citecolor: teal
    urlcolor: magenta
mainfont: Times New Roman
monofont: Courier New
editor: visual
editor_options: 
  chunk_output_type: console

execute:
  echo: false       # Muestra el código en los chunks
  warning: false   # Oculta advertencias
  message: false   # Oculta mensajes (ej. de librerías)
  eval: true       # Ejecuta los chunks
  cache: true 
---

```{=tex}
\thispagestyle{empty}
\vspace*{\fill}
\begin{center}
{\scshape\huge {Modelo Predictivo de Abandono de Clientes en el Sector de Telecomunicaciones usando Machine Learning en R}  \par\vspace{2cm}}
{\itshape\Large Trabajo Personal \par}
\vfill
{\Large Autor: \par}
{\large Juan Gabriel Carvajal Negrete \par\vspace{2cm}}
\vfill
\end{center}
\vspace*{\fill}
```

\newpage

```{r}
#| echo: false
#| warning: false
#| message: false

# Paquetes a usar 
require(magrittr)
require(tidyverse)
require(ggplot2)
require(psych)
```


## preprocesamiento de la imformacion 

```{r}
#| echo: false
datos <- read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv", header = TRUE, sep = ",")
```

La base de datos cuenta con **`r dim(datos)`** filas y columnas respectivamente 

